package com.example.demo.model;


import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@NoArgsConstructor
@Data
@DynamoDBTable(tableName = "usuarios")
public class Usuario {


    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String usuarioId;

    @DynamoDBAttribute
    private String nombre;
    @DynamoDBAttribute
    private String cedula;
}
