service: getUserLambda

provider:
  name: aws
  runtime: java17
  stage: dev
  region: us-east-2

functions:
  myLambdaFunction:
    handler: com.example.demo.LambdaHandler::handleRequest
    events:
      - http:
          path: /{proxy+}
          method: GET
          cors: false

