spring:
  application:
    name: getUserLambda
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
    h2:
      console:
        enabled: true
        path: /h2-console

aws:
  dynamodb:
    endpoint: dynamodb.us-east-2.amazonaws.com
  access:
    key: <aws_access_key_id>
    secret-key: <aws_secret_access_key>
  region: us-east-2
